// whatsnew.go
// Copyright(c) 2022-2024 vice contributors, licensed under the GNU Public License, Version 3.
// SPDX: GPL-3.0-only

package main

import "github.com/mmp/vice/pkg/renderer"

var whatsNew []string = []string{
	"Added EWR scenarios, including both departure and approach.",
	"Added Liberty departure scenarios.",
	"Improved routing of departures beyond their exit fix.",
	"Fixed a bug where aircraft on RNAV arrivals wouldn't descend.",
	"Each scenario has a default video map, selected automatically.",
	"If an aircraft given approach clearance is later vectored, approach clearance is now canceled.",
	"Improved spawn positions and hand-off locations for JFK arrivals.",
	"Added F11 TRACON scenarios (KMCO, KSFB, KISM, KORL...)",
	"Font sizes for UI elements can now be set in the settings window",
	"Fixed a crash related to handing off aircraft",
	"Added go arounds",
	"Added ABE TRACON scenarios",
	"Added scenarios for KJAX",
	"Updated PHL scenarios for recent arrival changes",
	"Fixed bug with localizer intercept that made aircraft hang in the air",
	"Fixed a few bugs in the KJAX scenario",
	"Added ISP and HVN departures and arrivals to the JFK_APP scenario",
	"Added LGA departure and arrival scenarios",
	"Vice now remembers the active aircraft when you quit and restores the simulation when you launch it again",
	"When vice is paused, hovering the mouse on a radar track shows the directions it has been given",
	"Fixed a bug where the STARS window wouldn't display anything",
	"All new flight modeling engine supports procedure turns and more accurate turns to intercept",
	"Updated approaches to include procedure turns, where appropriate",
	"Fixed very small fonts on Windows systems with high-DPI displays",
	"Added \"depart fix at heading\" and \"cross fix at altitude/speed\" commands",
	"Added \"cancel speed restrictions\" and \"fly present heading\" commands",
	"Handed-off departures don't start to climb until they are clicked post-handoff",
	"Improved wind modeling",
	"Fixed a bug that would cause arrivals to fly faster than the aircraft is capable of",
	"Fixed bugs with arrivals not obeying crossing restrictions",
	"Improved navigation model to better make crossing restrictions at fixes",
	"Fixed *T in the STARS scope: the line is drawn starting with the first click",
	"For facility engineers: an error is issued for any unused items in the scenario JSON files",
	"Added support for multi-controller simulations(!!)",
	"Added manual launch control option",
	"Many new scenarios added, including C90, CLE, and CLT",
	"Replaced the font used in the STARS radar scope",
	"Fixed a few graphics bugs in the STARS radar scope",
	"Fixed a rare crash with incorrect command input to the STARS scope",
	"New scenarios covering the A80 (ATL) and A90 (BOS) TRACONS",
	"Fixed a bug with drawing *P cones",
	"Many improvements to the STARS DCB implementation",
	"STARS now supports quick-look",
	"Fixed a rare crash when manually adjusting launch rates",
	"Numerous minor improvements to the STARS UI and functionality (including adding dwell mode)",
	"Small fixes to the JAX and CLT scenario files",
	"Added support for STARS FUSED mode (choose \"FUSED\" in the \"SITE\" menu in the DCB)",
	"New commands: EC/ED: expedite climb/descent",
	"New command: I: intercept the localizer",
	"New commands: SMIN/SMAX: maintain slowest practical / maximum forward speed",
	"New command: AFIX/CAPP: at FIX cleared APP approach",
	"Altitude crossing restrictions are more flexible: CFIX/A100-, CFIX/A80+, CFIX/A140-160, etc.",
	"Fixed a bug where arrivals would disappear with some scenarios",
	"Various updates to the JAX, C90, and F11 scenarios",
	"Added D01, KSAV, and KSDF scenarios",
	"Allow altitude and speed instructions to be either simultaneous or consecutive",
	"Added a new KAAC/KJKE scenario",
	"Various minor bugfixes and STARS simulation improvements",
	"Many improvements to the accuracy of the KAAC scenario",
	"Fixed a bug where arrivals would sometimes climb after being cleared for the approach",
	"Fixed a bug in the Windows installer that caused new scenarios (AAC, SAV, SDF) to not be installed locally",
	"Added the ability to draw active departure, arrival, and approach routes on the radar scope",
	"Added the D01 (Denver TRACON) scenario to single-user vice (the installer was missing it)",
	"Added support for updating your Discord activity based on your vice activities (thanks, Samuel Valencia!)",
	"Clicking the " + renderer.FontAwesomeIconKeyboard + " icon on the menubar gives a summary of vice's keyboard commands",
	"Fixed bug with aircraft descending too early when flying procedure turns",
	"Fixed bug with some departures trying to re-fly their initial departure route",
	"Fixed multiple bugs with the handling of \"at or above\" altitude constraints",
	"Fixed bug with the default DCB brightness being set to 0",
	"Added DCA scenario",
	"There is now a short delay before aircraft start to follow heading assignments",
	"Added \"ID\" command for ident",
	"Aircraft can now also be issued control commands by entering their callsign before the commands",
	"Fixed bugs with endless go-arounds and with departures not obeying altitude restrictions",
	"Fixed a bug that caused vice to sometimes crash after aircraft were given approach clearance",
	"Fixed a bug where descending aircraft would stop descending when given approach clearance",
	"Small fixes to the DCA scenario",
	"Polished up handling of early hand-offs of departures in the STARS scope",
	"Added L30 (Las Vegas) scenarios and a combined N90 (JFK+LGA+EWR) scenario",
	"Important readbacks from pilots are now highlighted in red",
	"Improved STARS *T to allow entering fix names and to show ETA",
	"Added support for charted visual approaches",
	"STARS allows control-shift click to initiate track (CRC style)",
	"Secondary scratchpads are now supported",
	"Fixed various navigation bugs",
	"STARS: fixed a bug where RBL lines for *T that included aircraft weren't drawn",
	"Added an option to hide the flight strips (Settings window, Flight Strips section)",
	"Fixed a bug where inbound handoffs wouldn't send a radio contact message",
	"Sped up loading of video maps so that vice launches more quickly",
	"Added multiple new scenarios: S46, BHM, GSP (Aaron Flett), AUS (Jace Martin), P50 (Mike K)",
	"Multi-controller servers can now be password-protected",
	"Added \"TO\" command for \"contact tower\"",
	"Various bugfixes with handoffs and approach navigation",
	"Match real-world STARS alert sounds",
	"Added new scenarios: D10 (Mike K), CYS, ASE, COS (Jud Lopez)",
	"Fixed multiple bugs with handling of altitude and speed restrictions in departure routes",
	"Increased acceleration and climb rate of departures to be more realistic",
	"Fixed multiple bugs with point outs",
	"Fixed bug in the STARS scope that required secondary scratchpads to be three characters",
	"(Re-)added optional sound effect for accepted handoffs",
	"Airspace warnings are inhibited for aircraft flying approaches",
	"STARS: allow control-left-click in place of the third mouse button to highlight aircraft",
	"STARS: actually use the LDB brightness setting for limited/partial datablocks",
	"STARS: fix incorrect error message after issuing \"at fix, cleared approach\"",
	"Added new scenarios: TPA (Connor Allen), SAN, SCT-BUR (Justin Nguyen), SCT (Eli Thompson), NCT, GJT (Jud Lopez)",
	"Smaller scenario updates: D10 and JAX (Mike K), AUS (Jace Martin), LGA, JFK, COS, CLE, ASE, DCA, F11",
	"Arc routes between fixes can now be accurately specified",
	"STARS: more accurate simulation of STARS weather radar display",
	"Added new syntax for issuing left/right turn in degrees: T10L, T20R, etc.",
	"STARS: allow middle-click highlight of aircraft regardless of having their track",
	"STARS: fixed bug with airport weather list flickering",
	"Added new scenarios: SCT LAX (Jud Lopez), IND (Samuel Valencia), MKE (Yahya Nazimuddin), MIA (Mike K)",
	"Scenario updates/bugfixes: TPA (Connor Allen), SCT ONT/SNA (Eli Thompson), A80, L30 (Michael Trokel)",
	"STARS: added automated terminal proximity alert (ATPA) support",
	"STARS: consolidated wake turbulence (CWT) categories are now shown in datablocks and used for ATPA in-trail requirements",
	"Live weather can now be used in sims",
	"STARS: fixed various small bugs related to when the FDB should be displayed",
	"New scenarios: BDL (MerryArbitrary), D21 (Jackson Verdoorn), M98 (Jace Martin), P80 (Ethan Malimon)",
	"Scenario updates: EWR (aq86_), LGA (Yi Zheng), MIA (Connor Allen), Y90 (MerryArbitrary, Nelson T)",
	`Aircraft control commands (like "C80" for "climb and maintain 8,000") must now start with a comma`,
	`Related: the scratchpad can now be set by entering text and slewing an aircraft`,
	"Redirected handoffs are now supported and inter- and intra-facility handoffs are now handled more accurately",
	`Added support for "force quicklook" to push a quicklook to another controller`,
	`Added support for minimum safe altitude warnings (MSAW) for aircraft that are below the MVA`,
	`CWT category updates and bugfixes`,
	`Added support for global leader lines`,
	`Limited datablocks are now supported (and used when appropriate)`,
	`Handle various cases where the FDB should be displayed by default`,
	`Fixed a bug where go-arounds would sometimes not contact departure`,
	`Fixed a bug where live weather would occasionally cause vice to crash`,
	`Fixed a bug where aircraft TAS would be too high at high altitudes`,
	`Added support for ATC chat (prefix chat messages a '/' in the command prompt)`,
	`Allow entering values for STARS DCB spinner using the keyboard`,
	`Scenario Updates: D01 and COS (Andrew S), Y90 (Merry Arbitrary), C90 (Jud Lopez, Yahya Nazimuddin)`,
	`Added "FC" command to tell aircraft to change to the next controller's frequency`,
	`STARS: Add support for displaying requested altitude in FDB`,
	`Fixed a bug where aircraft callsign numbers could start with 0`,
	`STARS: use realistic fonts for the STARS display`,
	`Improved sequencing of departures`,
	`Added I90 scenario (Jace Martin)`,
	`Added full-screen mode`,
	`Updated command entry so keyboard focus returns to STARS after issuing a control command`,
	`New scenarios: PIT (Gavin V), AVL, AGS, and GSO (Giovanni), ACK, BNA, BOS, CHS, MHT, OKC, RDU (Michael K)`,
	`Updates to BUF, CLE, D21 (Gavin), BHM (Giovanni), JAX and F11 (Michael K), D01 (Jud Lopez, Andrew S)`,
	`Even more scenario updates: C90 (Jud Lopez, Yahya Nazimuddin), A90 (Michael K)`,
	`STARS: more realistic video map handling (per controller maps, map id #s)`,
	`Fixed a bug where vice would crash on launch if it was exited while minimized`,
	`STARS: multiple improvements to drawing aircraft tracks`,
	`Added a short pause before aircraft ident`,
	`Aircraft can now be sent 'direct' to their destination airport`,
	`Fixed a bug where vice would sometimes crash at startup or when MAPS was clicked`,
	`New scenario: SCT (Jud Lopez)`,
	`Scenario updates: AVL (Giovanni), A90 and BOS (Michael K)`,
	`Fixed "ID" flashing when aircraft ident`,
	`New scenarios: MCI (Brody Carty), P31 (Josh Lambert)`,
	`Scenario updates: F11, JAX (Michael Knight), Y90 (Merry Aribrary)`,
	`Added "say altitude" (SA) and "say heading" commands (SH) (Michael Knight)`,
	`Aircraft delete ("X") is now a CLI command, not a STARS command (Michael Knight)`,
	`"Paste" is now supported in the messages pane (Michael Trokel)`,
	`The "\" key can be used in place of END to activate the STARS minimum separation tool`,
	`Fixed a bug where runway-specific routes in STARs would be followed too early`,
	`Fixed a bug where handoffs from virtual controllers would sometimes not be made`,
	`Anti-aliasing is disabled by default (but can be re-enabled via the "settings" menu)`,
	`Multiple fixes to improve accuracy of drawing in STARS`,
	`New scenarios: R90 (Logan S, Jackson Verdoorn), BOI (Jonah Lefkoff)`,
	`Scenario updates (1): M98 (Logan S, Jackson Verdoorn), MCI, N90 (Jud Lopez), D21, CLE (Gavin V)`,
	`Scenario updates (2): SAN (Justin Nguyen), D01 (Andrew S), MHT, ACK, A90 (Michael Knight), AAC`,
	`Added an underlying simulation of the NAS and STARS/ERAM computers`,
	`Multiple improvements to the realism of the STARS display and sounds`,
	`"Beaconator" added to STARS (F1)`,
	`Added "SQ" command to issue a beacon code to an aircraft`,
	`Fixed a crash when setting scratchpads`,
	`Fixed bugs in the "launch control window" that would prevent it from refreshing`,
	`New scenarios: CPR (Andrew S), CID (Tyler Temerowski)`,
	`Scenario updates (1): ASE, COS, CYS, D01 (Andrew S), N90 (Kayden Lambert), P50, A80 (radarcontacto)`,
	`Scenario updates (2): CDW (Mike LeGall), TPA, MIA (Connor Allen), F11 (Michael Knight), Y90 (Merry Arbitrary)`,
	`Fixed a crash on Windows systems with high-DPI displays`,
	`Fixed some cases where a procedure turn would be flown even after aircraft passed a "no pt" fix`,
	`STARS weather radar rendering is much closer to real-world`,
	`STARS: many small fixes to how datablocks and tracks / track ids are drawn`,
	`STARS: fixed some bugs where valid scratchpad entries were rejected`,
	`Fixed a crash when handing off to a different facility`,
	`Fixed a crash with corrupt Sim saves`,
	`Added airspace awareness information to the scenario information window`,
	`STARS: fixed colors for WX buttons in the DCB when WX is available`,
	`STARS: minor improvements to the rendering of tracks and position symbols`,
	`Fixed a crash loading saved scenarios from the last release`,
	`vice's documentation is substantially expanded and now discusses all currently-available functionality`,
	`STARS sign-on list is more realistic. The list of signed-on controllers can now be found in the "scenario info" window`,
	`STARS: multiple improvements to data block and radar track drawing accuracy`,
	`STARS: added support for inverted numpads on keyboards`,
	`STARS: fixed a number of bugs in "quicklook" and in MAPS and PREF management`,
	`Scenario updates: D10 (Austin Jenkins), EWR (Mike LeGall), CID (Tyler T), D01, COS (Andrew S), AAC`,
	`Massive update to the aircraft performance database (EkimWasHere)`,
	`The virtual local controllers sequence departures much better, including handling wake turbulence separation`,
	`Multiple improvements to the aircraft flight model`,
	`STARS: added support for coordination lists (used for "hold for release")`,
	`STARS: improved handling of preference sets: a separate one is stored for each TRACON`,
	`Multiple improvements to the accuracy of flight strips`,
	`New scenario: SGF (Tyler T)`,
	`Updated how aircraft control instructions are entered: press ; to enable "target generation" mode in STARS`,
	`New scenario: LGA HAARP (Tyler T)`,
	`Scenario updates: CHS, F11 (Michael Knight), SCT, C90, MKE (Jud Lopez)`,
	`Fixed a bug where aircraft that went around after being handed off to tower wouldn't contact tower the next time`,
	`Fixed a few bugs related to the 250kts speed limit at 10,000'`,
	`Added more compact "hold for release" interface for airports that don't use STARS coordination lists`,
	`STARS: added OJTI mode, where an instructor can sign in and issue commands to all aircraft`,
	`STARS: added support for restriction areas`,
	`STARS: multiple improvements to video map handling, including supporting multiple colors and map categories`,
	`STARS: CA and MSAW alerts are no longer generated for unassociated tracks`,
	`New scenarios: MDT (Darius L), PVD (radarcontacto)`,
	`Scenario updates: DCA (radarcontacto), SCT (Aiden), JFK airspace (Mike LeGall), Y90 (Merry), L30, NCT, P80, SCT, SDF (Ketan K)`,
	`Airspace boundaries are now displayed using the scenario information window`,
	`Improve fetching of airport weather (Makoto Sakaguchi)`,
	`Fixed a bug that was causing vice to crash when loading saved sims`,
	`Fixed a bug where departures would climb beyond upcoming altitude constraints in SIDs`,
	`Fixed a bug where aircraft would incorrectly descend along an approach they weren't yet cleared for`,
	`Fixed multiple bugs with the launch control window`,
	`Removed text input from the messages pane: it's back to just printing radio calls and messages`,
	`Updated handoffs so that there is a delay of 5-10 seconds before aircraft call in after the track is accepted`,
	`STARS: continue to display the id for external facility handoffs in datablocks for a few seconds`,
	`STARS: improved the accuracy of the mapping of precipitation to WX levels`,
	`STARS: a partial callsign is given to specify an aircraft to be given an instruction, it must be a unique suffix of a callsign`,
	`STARS: OJTI mode now available where an instructor can issue aircraft control commands (Michael Trokel)`,
	`New scenario: SBA (Ketan K)`,
	`Scenario updates: SAN, BUR, NCT, L30 (Ketan K), EWR, JFK (Mike LeGall), JAX (Jud Lopez), D01, GJT, ASE, COS (Andrew S), MDT (Darius L), A90 (radarcontacto)`,
	`Aircraft can now intercept the approach for non-ILS approaches`,
	`Aircraft will now intercept an approach if they are direct to a fix on it`,
	`Fixed bug where overflights would be climbed to their cruising altitude`,
	`Aircraft wait 5-10 seconds before changing their beacon codes when a new one is assigned`,
	`Fixed bug where departures would climb prematurely`,
	`Aircraft that are too high when they cross the threshold go missed`,
	`Fix bug with delayed descents when aircraft are cleared for the approach after being told to intercept`,
	`An audio alert can now be optionally played when aircraft check in or transmit radio messages`,
	`STARS: Multiple bug fixes to how point outs are shown`,
	`STARS: Flash "DB" in data blocks for duplicate beacon codes`,
	`STARS: Point outs can now be recalled by slewing the target.`,
}
