// pkg/platform/imgui.go
// Copyright(c) 2022-2024 vice contributors, licensed under the GNU Public License, Version 3.
// SPDX: GPL-3.0-only
package platform

import "github.com/AllenDang/cimgui-go/imgui"

var imguiKeyNames = map[imgui.Key]string{
	imgui.KeyTab:           "Tab",
	imgui.KeyLeftArrow:     "Left Arrow",
	imgui.KeyRightArrow:    "Right Arrow",
	imgui.KeyUpArrow:       "Up Arrow",
	imgui.KeyDownArrow:     "Down Arrow",
	imgui.KeyPageUp:        "Page Up",
	imgui.KeyPageDown:      "Page Down",
	imgui.KeyHome:          "Home",
	imgui.KeyEnd:           "End",
	imgui.KeyInsert:        "Insert",
	imgui.KeyDelete:        "Delete",
	imgui.KeyBackspace:     "Backspace",
	imgui.KeySpace:         "Space",
	imgui.KeyEnter:         "Enter",
	imgui.KeyEscape:        "Escape",
	imgui.KeyApostrophe:    "Apostrophe",
	imgui.KeyComma:         "Comma",
	imgui.KeyMinus:         "Minus",
	imgui.KeyPeriod:        "Period",
	imgui.KeySlash:         "Slash",
	imgui.KeySemicolon:     "Semicolon",
	imgui.KeyEqual:         "Equal",
	imgui.KeyLeftBracket:   "Left Bracket",
	imgui.KeyBackslash:     "Backslash",
	imgui.KeyOem102:        "OEM 102",
	imgui.KeyRightBracket:  "Right Bracket",
	imgui.KeyGraveAccent:   "Grave Accent",
	imgui.KeyCapsLock:      "Caps Lock",
	imgui.KeyScrollLock:    "Scroll Lock",
	imgui.KeyNumLock:       "Num Lock",
	imgui.KeyPrintScreen:   "Print Screen",
	imgui.KeyPause:         "Pause",
	imgui.KeyKeypad0:       "Keypad 0",
	imgui.KeyKeypad1:       "Keypad 1",
	imgui.KeyKeypad2:       "Keypad 2",
	imgui.KeyKeypad3:       "Keypad 3",
	imgui.KeyKeypad4:       "Keypad 4",
	imgui.KeyKeypad5:       "Keypad 5",
	imgui.KeyKeypad6:       "Keypad 6",
	imgui.KeyKeypad7:       "Keypad 7",
	imgui.KeyKeypad8:       "Keypad 8",
	imgui.KeyKeypad9:       "Keypad 9",
	imgui.KeyKeypadDecimal: "Keypad Decimal",
	imgui.KeyKeypadDivide:  "Keypad Divide",
	imgui.KeyKeypadMultiply:"Keypad Multiply",
	imgui.KeyKeypadSubtract:"Keypad Subtract",
	imgui.KeyKeypadAdd:     "Keypad Add",
	imgui.KeyKeypadEnter:   "Keypad Enter",
	imgui.KeyKeypadEqual:   "Keypad Equal",
	imgui.KeyLeftShift:     "Left Shift",
	imgui.KeyLeftCtrl:      "Left Control",
	imgui.KeyLeftAlt:       "Left Alt",
	imgui.KeyLeftSuper:     "Left Super",
	imgui.KeyRightShift:    "Right Shift",
	imgui.KeyRightCtrl:     "Right Control",
	imgui.KeyRightAlt:      "Right Alt",
	imgui.KeyRightSuper:    "Right Super",
	imgui.KeyMenu:          "Menu",
	imgui.Key0:             "0",
	imgui.Key1:             "1",
	imgui.Key2:             "2",
	imgui.Key3:             "3",
	imgui.Key4:             "4",
	imgui.Key5:             "5",
	imgui.Key6:             "6",
	imgui.Key7:             "7",
	imgui.Key8:             "8",
	imgui.Key9:             "9",
	imgui.KeyA:             "A",
	imgui.KeyB:             "B",
	imgui.KeyC:             "C",
	imgui.KeyD:             "D",
	imgui.KeyE:             "E",
	imgui.KeyF:             "F",
	imgui.KeyG:             "G",
	imgui.KeyH:             "H",
	imgui.KeyI:             "I",
	imgui.KeyJ:             "J",
	imgui.KeyK:             "K",
	imgui.KeyL:             "L",
	imgui.KeyM:             "M",
	imgui.KeyN:             "N",
	imgui.KeyO:             "O",
	imgui.KeyP:             "P",
	imgui.KeyQ:             "Q",
	imgui.KeyR:             "R",
	imgui.KeyS:             "S",
	imgui.KeyT:             "T",
	imgui.KeyU:             "U",
	imgui.KeyV:             "V",
	imgui.KeyW:             "W",
	imgui.KeyX:             "X",
	imgui.KeyY:             "Y",
	imgui.KeyZ:             "Z",
	imgui.KeyF1:            "F1",
	imgui.KeyF2:            "F2",
	imgui.KeyF3:            "F3",
	imgui.KeyF4:            "F4",
	imgui.KeyF5:            "F5",
	imgui.KeyF6:            "F6",
	imgui.KeyF7:            "F7",
	imgui.KeyF8:            "F8",
	imgui.KeyF9:            "F9",
	imgui.KeyF10:           "F10",
	imgui.KeyF11:           "F11",
	imgui.KeyF12:           "F12",
	imgui.KeyF13:           "F13",
	imgui.KeyF14:           "F14",
	imgui.KeyF15:           "F15",
	imgui.KeyF16:           "F16",
	imgui.KeyF17:           "F17",
	imgui.KeyF18:           "F18",
	imgui.KeyF19:           "F19",
	imgui.KeyF20:           "F20",
	imgui.KeyF21:           "F21",
	imgui.KeyF22:           "F22",
	imgui.KeyF23:           "F23",
	imgui.KeyF24:           "F24",
	imgui.KeyNone:          "None",
}

func GetImGuiKeyName(key imgui.Key) string {
    if name, ok := imguiKeyNames[key]; ok {
        return name
    }
	return ""
}