// wx/facilities.go
// Copyright(c) vice contributors, licensed under the GNU Public License, Version 3.
// SPDX: GPL-3.0-only

package wx

import (
	"encoding/json"
	"errors"
	"fmt"
	"io"
	"os"
	"slices"
	"time"

	"github.com/mmp/vice/aviation/db"
	"github.com/mmp/vice/util"
)

// atmosExcludedARTCCs are ARTCCs skipped for atmos ingest.
var atmosExcludedARTCCs = []string{
	"ZAE", // Anchorage Oceanic: outside HRRR coverage
}

// FacilityRegion returns the region the facility is in, "conus", "alaska",
// or "hawaii", which determines where its radar images and atmospheric data
// come from. There is no HRRR for Hawaii; its atmospheric data comes from the
// NAM's Hawaii nest.
func FacilityRegion(facility string) string {
	switch facility {
	case "A11", "FAI", "ZAN":
		return "alaska"
	case "HNL", "ITO", "OGG", "ZHN":
		return "hawaii"
	default:
		return "conus"
	}
}

// AtmosInterval returns how often the facility has atmospheric data. The
// CONUS HRRR is issued hourly, the Alaska HRRR every three hours (00Z, 03Z,
// ...), and the NAM Hawaii nest every six (00Z, 06Z, 12Z, 18Z).
func AtmosInterval(facility string) time.Duration {
	switch FacilityRegion(facility) {
	case "alaska":
		return 3 * time.Hour
	case "hawaii":
		return 6 * time.Hour
	default:
		return time.Hour
	}
}

// Facilities records the airports and facilities that vice's weather pipeline
// covers. wxingest runs from a container image that can't carry the video maps
// that loading the scenarios validates against, so the list is generated by
// "viceserver -wxfacilities" where the full resources are available and is
// passed to both it and wxpackage as a file.
type Facilities struct {
	Airports []string `json:"airports"` // METAR
	TRACONs  []string `json:"tracons"`  // atmos
	ARTCCs   []string `json:"artccs"`   // atmos and TFRs
}

// MakeFacilities returns the weather coverage implied by the airports and
// TRACONs that have vice scenarios. Unlike TRACONs, the ARTCCs don't consider
// which have scenarios: center scenarios are under active development and
// pre-ingesting spares us historical backfills as they arrive.
func MakeFacilities(airports, tracons []string) Facilities {
	// Not currently needed but let's save ourselves the trouble of
	// downloading all the Alaska gribs again if an FAI scenario is added.
	tracons = append(tracons, "FAI")

	return Facilities{
		Airports: sortedUnique(airports),
		TRACONs:  sortedUnique(tracons),
		ARTCCs: util.FilterSlice(util.SortedMapKeys(db.DB.ARTCCs), func(id string) bool {
			return !slices.Contains(atmosExcludedARTCCs, id)
		}),
	}
}

func sortedUnique(s []string) []string {
	s = util.DuplicateSlice(s)
	slices.Sort(s)
	return slices.Compact(s)
}

// ReadFacilities reads the facility list written by
// "viceserver -wxfacilities".
func ReadFacilities(path string) (Facilities, error) {
	b, err := os.ReadFile(path)
	if err != nil {
		return Facilities{}, fmt.Errorf("%s: %w", path, err)
	}

	var f Facilities
	if err := util.UnmarshalJSONBytes(b, &f); err != nil {
		return Facilities{}, fmt.Errorf("%s: %w", path, err)
	}
	// An empty list would silently ingest or package nothing at all.
	if len(f.TRACONs) == 0 || len(f.ARTCCs) == 0 || len(f.Airports) == 0 {
		return Facilities{}, fmt.Errorf("%s: %w", path, errors.New("no airports or facilities"))
	}

	return f, nil
}

// Write encodes the facility list as JSON.
func (f Facilities) Write(w io.Writer) error {
	enc := json.NewEncoder(w)
	enc.SetIndent("", "  ")
	return enc.Encode(f)
}
