// wx/facilities.go
// Copyright(c) 2022-2026 vice contributors, licensed under the GNU Public License, Version 3.
// SPDX: GPL-3.0-only

package wx

import (
	"encoding/json"
	"errors"
	"fmt"
	"io"
	"os"
	"slices"

	av "github.com/mmp/vice/aviation"
	"github.com/mmp/vice/util"
)

// atmosExcludedTRACONs are TRACONs with vice scenarios that are nonetheless
// skipped for atmos ingest.
var atmosExcludedTRACONs = []string{
	// NOAA uses a currently unsupported grib2 grid format for Hawaii.
	"HNL", "OGG",
}

// atmosExcludedARTCCs are ARTCCs skipped for atmos ingest.
var atmosExcludedARTCCs = []string{
	"ZHN", // NOAA uses a currently unsupported grib2 grid format for Hawaii
	"ZAE", // Anchorage Oceanic: outside HRRR coverage
}

// Facilities records the airports and facilities that vice's weather pipeline
// covers. wxingest runs from a container image that can't carry the video maps
// that loading the scenarios validates against, so the list is generated by
// "viceserver -wxfacilities" where the full resources are available and is
// passed to both it and wxpackage as a file.
type Facilities struct {
	Airports []string `json:"airports"` // METAR
	TRACONs  []string `json:"tracons"`  // atmos
	ARTCCs   []string `json:"artccs"`   // atmos and TFRs
}

// MakeFacilities returns the weather coverage implied by the airports and
// TRACONs that have vice scenarios. Unlike TRACONs, the ARTCCs don't consider
// which have scenarios: center scenarios are under active development and
// pre-ingesting spares us historical backfills as they arrive.
func MakeFacilities(airports, tracons []string) Facilities {
	tracons = util.FilterSlice(tracons, func(id string) bool {
		return !slices.Contains(atmosExcludedTRACONs, id)
	})
	// Not currently needed but let's save ourselves the trouble of
	// downloading all the Alaska gribs again if an FAI scenario is added.
	tracons = append(tracons, "FAI")

	return Facilities{
		Airports: sortedUnique(airports),
		TRACONs:  sortedUnique(tracons),
		ARTCCs: util.FilterSlice(util.SortedMapKeys(av.DB.ARTCCs), func(id string) bool {
			return !slices.Contains(atmosExcludedARTCCs, id)
		}),
	}
}

func sortedUnique(s []string) []string {
	s = util.DuplicateSlice(s)
	slices.Sort(s)
	return slices.Compact(s)
}

// ReadFacilities reads the facility list written by
// "viceserver -wxfacilities".
func ReadFacilities(path string) (Facilities, error) {
	b, err := os.ReadFile(path)
	if err != nil {
		return Facilities{}, fmt.Errorf("%s: %w", path, err)
	}

	var f Facilities
	if err := util.UnmarshalJSONBytes(b, &f); err != nil {
		return Facilities{}, fmt.Errorf("%s: %w", path, err)
	}
	// An empty list would silently ingest or package nothing at all.
	if len(f.TRACONs) == 0 || len(f.ARTCCs) == 0 || len(f.Airports) == 0 {
		return Facilities{}, fmt.Errorf("%s: %w", path, errors.New("no airports or facilities"))
	}

	return f, nil
}

// Write encodes the facility list as JSON.
func (f Facilities) Write(w io.Writer) error {
	enc := json.NewEncoder(w)
	enc.SetIndent("", "  ")
	return enc.Encode(f)
}
